version: '3.7'

networks:
  db_network:


volumes:
  data_volume:
    driver: local
    driver_opts:
      type: none
      device: data/postgres_db
      o: bind

services:
  postgres_db:
    build: docker/postgres12
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "9999:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data
    env_file:
      - docker/postgres12/postgres.env
    networks:
      - db_network
